---
functional:
  - требование 1 Пользователь должен иметь возможность играть с другим пользователем 
  - требование 2 Пользователь должен иметь возможность играть с ботом
  - требование 3 Пользователь должен иметь возможность просматривать рейтинг и информацию о игровом статусе
  - требование 4 Пользователь должен иметь возможность видеть написание кода друг у друга
non-functional:
  - требование 5 Сайт должен быть безопасным и защищать данные пользователя
  - требование 6 Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - требование 8 Сайт должен иметь мобильную версию
  - требование 9 Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - требование 10 Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - требование 5 Реагирование веб-сайта на низкую скорость интернета или его отсутствие
